navigation:
    menu_config:
        items:
            system_configuration:
                label:    'pintushi.config.menu.system_configuration.label'
                position: 10
                extras:
                    description: 'pintushi.config.menu.system_configuration.description'
                route: 'api_system_configuration_tree'

        tree:
            application_menu:
                children:
                    system_tab:
                        children:
                            system_configuration: ~
